# Generated by Django 5.2.4 on 2025-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
